databases:
    prod:
        driver: mysql
        host: localhost
        database: database
        username: root
        password: secret
        charset: utf8
        collation: utf8_unicode_ci
    local:
        driver: mysql
        host: localhost
        database: database
        username: root
        password: secret
        charset: utf8
        collation: utf8_unicode_ci
